### ISSUE TITLE
Views with PermissionRequiredMixin incorrectly tries to direct to login page

### ISSUE THREAD

**Issue by profcturner** [profcturner/WAM#22]
Some newer views user the PermissionRequiredMixin. Logged in users without the permission are automatically redirected to a missing login page.

They should be cleanly informed that they don't have the permission.

**Comment by profcturner** [comment]
This is quite puzzling because the Django source code shows:

```
def handle_no_permission(self):
        if self.raise_exception or self.request.user.is_authenticated:
            raise PermissionDenied(self.get_permission_denied_message())
        return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())

```

so that this redirection should only happen is the user is not authenticated, but this is happening with authenticated users.

**Comment by qofsq** [comment]
def handle_no_permission(self):
        if self.raise_exception or **self.request.user.is_authenticated**:
            raise PermissionDenied(self.get_permission_denied_message())
        return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())

I’m probably wrong, as I haven’t looked at what the bold function returns, but that to me says ‘if the user is authenticated then raise the denied exception and return to login page’. Should that maybe be checking for ‘not’ self.request.user.is_authenticated?

**Comment by profcturner** [comment]
It looks like this behaviour is intended as a feature, in order to allow users to re-login with higher level permissions, but it's a bit of a pain and I could do with finding a way to avoid it.

**Comment by profcturner** [comment]
But... it seems to be behaving better since I added 403.html and 404.html templates, so I'm closing this for now.
